### ISSUE TITLE
code convert to Color add zeroes bug

### ISSUE THREAD

**Issue by hocgin** [gabrie-allaigre/avatar-generator#1]
![image](https://user-images.githubusercontent.com/16535610/77736015-90591400-7046-11ea-9f20-36ef2a218903.png)

### This Code
```java
public class Avatars {
    public static final Avatar AVATAR = GitHubAvatar.newAvatarBuilder()
        .build();

    public static File getAvatarFile(long code) {
        return getFile(Avatars.AVATAR, code);
    }

    private static File getFile(Avatar avatar, long code) {
        int size = avatar.getWidth();
        BufferedImage dest = new BufferedImage(size, size, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = dest.createGraphics();
        AvatarUtils.activeAntialiasing(g2);
        g2.drawImage(avatar.create(code), 0,  0, size, size, null);
        g2.dispose();
        return toFile(dest);
    }

    private static File toFile(BufferedImage bi) {
        Path file;
        try {
            file = Files.createTempFile("img", ".png");
            ImageIO.write(bi, "png", file.toFile());
            return file.toFile();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    public static void main(String[] args) throws IOException {
        final File avatarFile = getAvatarFile(0L);
        Desktop.getDesktop().open(avatarFile);
    }
}
```

### This Exception
```java
Exception in thread "main" com.talanlabs.avatargenerator.AvatarException: Failed to build avatar
	at com.talanlabs.avatargenerator.Avatar.buildAll(Avatar.java:128)
	at com.talanlabs.avatargenerator.Avatar.create(Avatar.java:71)
	at in.hocg.eagle.basic.lang.Avatars.getFile(Avatars.java:34)
	at in.hocg.eagle.basic.lang.Avatars.getAvatarFile(Avatars.java:26)
	at in.hocg.eagle.basic.lang.Avatars.main(Avatars.java:51)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 6
	at java.lang.String.substring(String.java:1963)
	at com.talanlabs.avatargenerator.utils.AvatarUtils.extractColor(AvatarUtils.java:196)
	at com.talanlabs.avatargenerator.element.GitHubElementRegistry.buildImage(GitHubElementRegistry.java:32)
	at com.talanlabs.avatargenerator.element.AbstractImageElementRegistry.getElement(AbstractImageElementRegistry.java:21)
	at com.talanlabs.avatargenerator.Avatar.buildAvatarImage(Avatar.java:150)
	at com.talanlabs.avatargenerator.Avatar.buildAll(Avatar.java:108)
	... 4 more
```

**Comment by gabrie-allaigre** [comment]
Hi,
addZeroes must be corrected
